apiVersion: v1
kind: Service

metadata:
  labels:
    app: kibana
  name: kibana-srv

spec:
    type: NodePort
    ports:
        - port: 5601
          targetPort: 5601
          nodePort: 30004
    selector:
        app: kibana
