apiVersion: v1
kind: Service

metadata:
  labels: {{ include "mies.extralabels" .Values.kibana.extraLabels | nindent 4}}
    app: {{ include "mies.kibanalabel" . }}
  name: {{ include "mies.kibanaservicename" . }}

spec:
    type: {{ .Values.kibana.service.type }}
    ports:
        - port: {{ .Values.kibana.service.port }}
          targetPort: {{ .Values.kibana.service.targetPort }}
          {{- if .Values.kibana.service.nodePort }}
          nodePort: {{ .Values.kibana.service.nodePort }}
          {{- end }}
    selector:
        app:  {{ include "mies.kibanalabel" . }}


# NOMBRE DEL SERVICIO:


