---
# Source: mies/templates/secrets.yaml
kind: Secret
apiVersion: v1

metadata:
    name:  RELEASE-NAME-secret

data:
    user: "ZWxhc3RpYw=="
    password: "UnhjWnJDSjd1R1VYR05X"
---
# Source: mies/templates/elasticsearch/master/service.yaml
apiVersion: v1
kind: Service

metadata:
  labels:
    app:  RELEASE-NAME-elasticsearch-maestro
  name: RELEASE-NAME-elasticsearch-maestro-srv

spec:
    type: ClusterIP
    ports:
        - name: externo
          port: 9200
          targetPort: 9200
        - name: interno
          port: 9300
          targetPort: 9300
    selector:
        app: 
             RELEASE-NAME-elasticsearch-maestro
---
# Source: mies/templates/kibana/service.yaml
apiVersion: v1
kind: Service

metadata:
  labels:
    app: RELEASE-NAME-kibana
  name: RELEASE-NAME-kibana-srv

spec:
    type: ClusterIP
    ports:
        - port: 5601
          targetPort: 5601
    selector:
        app:  RELEASE-NAME-kibana


# NOMBRE DEL SERVICIO:
---
# Source: mies/templates/kibana/deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app:  RELEASE-NAME-kibana
  name:  RELEASE-NAME-kibana

spec:
  replicas: 1
  selector:
    matchLabels:
      app:  RELEASE-NAME-kibana
      
  template:
    metadata:
      labels:
        app:  RELEASE-NAME-kibana
        
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:7.8.0
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elastic-coordinador:9200"
        - name:  SERVER_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
        - name:  SERVER_HOST
          valueFrom:
            fieldRef:
                fieldPath: metadata.name

        - name:  ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
                name: secreto-elastic 
                key:  user
                
        - name:  ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
                name: secreto-elastic 
                key:  password
---
# Source: mies/templates/elasticsearch/master/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet

metadata:
  labels:
    app: RELEASE-NAME-elasticsearch-maestro
  name: RELEASE-NAME-elasticsearch-maestro

spec:
  replicas: 3
  
  serviceName: RELEASE-NAME-elasticsearch-maestro-srv
  
  selector:
    matchLabels:
      app:  RELEASE-NAME-elasticsearch-maestro
      
  template:
    metadata:
      labels:
        app:  RELEASE-NAME-elasticsearch-maestro
        
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        ports:
        - containerPort: 9300
        - containerPort: 9200
        env:
        - name: node.name
          valueFrom:
            fieldRef:
                fieldPath: metadata.name

        - name:  cluster.name
          value: mi-cluster
          
        - name:  discovery.seed_hosts
          value: elastic-maestro-0.RELEASE-NAME-elasticsearch-maestro-srv,elastic-maestro-1.RELEASE-NAME-elasticsearch-maestro-srv,elastic-maestro-2.RELEASE-NAME-elasticsearch-maestro-srv
          
        - name:  cluster.initial_master_nodes
          value: elastic-maestro-0,elastic-maestro-1,elastic-maestro-2

        - name:  ES_JAVA_OPTS
          value: "-Xms220m -Xmx220m"
          
        - name:  node.master
          value: "true"
        - name:  node.voting_only
          value: "false"
        - name:  node.data
          value: "false"
        - name:  node.ingest
          value: "false"
        - name:  node.remote_cluster_client
          value: "false"

        - name:  xpack.security.enabled
          value: "true"
        - name:  ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
                name: secreto-elastic 
                key:  password                
        volumeMounts:      
        - name: datos-maestros
          mountPath: /usr/share/elasticsearch/data
  
  volumeClaimTemplates:
    - metadata:
        name: datos-maestros
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
        storageClassName:
