---
# Source: mies/templates/secrets.yaml
kind: Secret
apiVersion: v1

metadata:
    name:  RELEASE-NAME-secret

data:
    user: "ZWxhc3RpYw=="
    password: "d01hUXdHRWp5YW1IYzI4"
---
# Source: mies/templates/elasticsearch/configmap.yaml
kind: ConfigMap
apiVersion: v1

metadata:
    name:  RELEASE-NAME-elasticsearch-data-configmap

data:   
    otra_propiedad: "con su valor"
    ES_JAVA_OPTS: "-Xms500m -Xmx500m"
---
# Source: mies/templates/elasticsearch/configmap.yaml
kind: ConfigMap
apiVersion: v1

metadata:
    name:  RELEASE-NAME-elasticsearch-master-configmap

data:   
    otra_propiedad: "con su valor"
    ES_JAVA_OPTS: "-Xms220m -Xmx220m"
---
# Source: mies/templates/elasticsearch/master/service.yaml
apiVersion: v1
kind: Service


metadata:
  labels: 
    label1: "value1"
    app: RELEASE-NAME-elasticsearch-master
  
  name: RELEASE-NAME-elasticsearch-master-srv
  
spec:
    type: ClusterIP
    ports:
        - name: externo
          port: 9200
          targetPort: 9200
        - name: interno
          port: 9300
          targetPort: 9300
    selector:
        app: RELEASE-NAME-elasticsearch-master
---
# Source: mies/templates/elasticsearch/service.yaml
kind: Service
apiVersion: v1

metadata:
  labels: 
    app: RELEASE-NAME-elasticsearch-ingest
  
  name: RELEASE-NAME-elasticsearch-ingest-srv
  
spec:
    type: ClusterIP
    ports:
        - name: externo
          port: 9200
          targetPort: 9200
    selector:
        app: RELEASE-NAME-elasticsearch-data   
        #### 
        ### Servicio de ingesta: app:  Statefulset de Ingesta o en su lugar 
        # RELEASE-NAME-elasticsearch-data
        # RELEASE-NAME-elasticsearch-ingest
        ###
---
# Source: mies/templates/elasticsearch/service.yaml
kind: Service
apiVersion: v1

metadata:
  labels: 
    app: RELEASE-NAME-elasticsearch-query
  
  name: RELEASE-NAME-elasticsearch-query-srv
  
spec:
    type: ClusterIP
    ports:
        - name: externo
          port: 9200
          targetPort: 9200
    selector:
        app: RELEASE-NAME-elasticsearch-data   
        #### 
        ### Servicio de ingesta: app:  Statefulset de Ingesta o en su lugar 
        # RELEASE-NAME-elasticsearch-data
        # RELEASE-NAME-elasticsearch-ingest
        ###
---
# Source: mies/templates/kibana/service.yaml
apiVersion: v1
kind: Service

metadata:
  labels: 
    mode: "Ivan"
    mode2: "Ivancito"
    app: RELEASE-NAME-kibana
  name: RELEASE-NAME-kibana-srv

spec:
    type: ClusterIP
    ports:
        - port: 5601
          targetPort: 5601
    selector:
        app:  RELEASE-NAME-kibana


# NOMBRE DEL SERVICIO:
---
# Source: mies/templates/kibana/deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  labels: 
    mode: "Ivan"
    mode2: "Ivancito"
    app:  RELEASE-NAME-kibana
  name:  RELEASE-NAME-kibana

spec:
  replicas: 1
  selector:
    matchLabels:
      app:  RELEASE-NAME-kibana
      
  template:
    metadata:
      labels: 
        mode: "Ivan"
        mode2: "Ivancito"
        app:  RELEASE-NAME-kibana

    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:7.8.0
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elastic-coordinador:9200"
        - name:  SERVER_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
        - name:  SERVER_HOST
          valueFrom:
            fieldRef:
                fieldPath: metadata.name

        - name:  ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
                name: RELEASE-NAME-secret 
                key:  user
                
        - name:  ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
                name: RELEASE-NAME-secret 
                key:  password
---
# Source: mies/templates/elasticsearch/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet

metadata:
  labels: 
    app: RELEASE-NAME-elasticsearch-data
  name: RELEASE-NAME-elasticsearch-data

spec:
  replicas: 2
  serviceName: qklcqihkcj
  selector:
    matchLabels:
      app:  RELEASE-NAME-elasticsearch-data
      
      

  template:
    metadata:
      labels: 
        app:  RELEASE-NAME-elasticsearch-data
        
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        ports:
        - containerPort: 9300
        - containerPort: 9200
        envFrom:
            - configMapRef:
                name: RELEASE-NAME-elasticsearch-data-configmap        
        env:
        - name: node.name
          valueFrom:
            fieldRef:
                fieldPath: metadata.name

        - name:  cluster.name
          value: mi-cluster
        - name:  discovery.seed_hosts
          value: elastic-maestro-0.RELEASE-NAME-elasticsearch-master-srv,elastic-maestro-1.RELEASE-NAME-elasticsearch-master-srv,elastic-maestro-2.RELEASE-NAME-elasticsearch-master-srv
          
        - name:  node.master
          value:  "false" 
        - name:  node.voting_only
          value: "false"
        - name:  node.data
          value: "true"
        - name:  node.ingest
          value:  "false" 
        - name:  node.remote_cluster_client
          value: "false"

        - name:  xpack.security.enabled
          value: "true"
        - name:  ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
                name: RELEASE-NAME-secret 
                key:  password
---
# Source: mies/templates/elasticsearch/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet

metadata:
  labels: 
    label1: "value1"
    app: RELEASE-NAME-elasticsearch-master
  name: RELEASE-NAME-elasticsearch-master

spec:
  replicas: 3
    
  serviceName: RELEASE-NAME-elasticsearch-master-srv
  selector:
    matchLabels:
      app:  RELEASE-NAME-elasticsearch-master
      
      

  template:
    metadata:
      labels: 
        label1: "value1"
        app:  RELEASE-NAME-elasticsearch-master
        
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        ports:
        - containerPort: 9300
        - containerPort: 9200
        envFrom:
            - configMapRef:
                name: RELEASE-NAME-elasticsearch-master-configmap        
        env:
        - name: node.name
          valueFrom:
            fieldRef:
                fieldPath: metadata.name

        - name:  cluster.name
          value: mi-cluster
        - name:  cluster.initial_master_nodes
          value: elastic-maestro-0,elastic-maestro-1,elastic-maestro-2
        - name:  discovery.seed_hosts
          value: elastic-maestro-0.RELEASE-NAME-elasticsearch-master-srv,elastic-maestro-1.RELEASE-NAME-elasticsearch-master-srv,elastic-maestro-2.RELEASE-NAME-elasticsearch-master-srv
          
        - name:  node.master
          value: "true"
        - name:  node.voting_only
          value: "false"
        - name:  node.data
          value:  "false" 
        - name:  node.ingest
          value:  "false" 
        - name:  node.remote_cluster_client
          value: "false"

        - name:  xpack.security.enabled
          value: "true"
        - name:  ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
                name: RELEASE-NAME-secret 
                key:  password
