{{ if (empty .Values.auth.existentSecretName) }}

kind: Secret
apiVersion: v1

metadata:
    name:  {{ include "mies.secret" . }}

data:
    {{ required "Debe introducir un valor para el nombre de la clave del USUARIO en el SECRET: auth.userNameKey !!!" .Values.auth.userNameKey }}: {{ required "Debe introducir un valor para el usuario de elasticSearch: auth.userNameValue !!!" .Values.auth.userNameValue | b64enc | quote }}
    {{- if (empty .Values.auth.passwordValue) }}
    {{ required "Debe introducir un valor para el nombre de la clave del PASSWORD en el SECRET: auth.passwordKey !!!" .Values.auth.passwordKey }}: {{ randAlphaNum 15 | b64enc | quote }}
    {{- else }}
    {{ required "Debe introducir un valor para el nombre de la clave del PASSWORD en el SECRET: auth.passwordKey !!!" .Values.auth.passwordKey }}: {{ .Values.auth.passwordValue | b64enc | quote }}
    {{ end }}
    
{{ end }}
