apiVersion: v1
kind: Service

metadata:
  labels: {{ include "mies.extralabels" .Values.elasticsearch.master.extraLabels | nindent 4}}
    app:  {{ include "mies.elasticsearchmaestrolabel" . }}
  name: {{ include "mies.elasticsearchmaestroservicename" . }}

spec:
    type: ClusterIP
    ports:
        - name: externo
          port: {{ required "Debe introducir un valor para el puerto externo de comunicaciones de ElastiSearch: elasticsearch.ports.external !!!" .Values.elasticsearch.ports.external }}
          targetPort: {{ .Values.elasticsearch.ports.external }}
        - name: interno
          port: {{ required "Debe introducir un valor para el puerto interno de comunicaciones de ElastiSearch: elasticsearch.ports.internal !!!" .Values.elasticsearch.ports.internal }}
          targetPort: {{ .Values.elasticsearch.ports.internal }}
    selector:
        app: 
             {{ include "mies.elasticsearchmaestrolabel" . }}
 