{{ range $tipo_nodo, $especificacion := dict "master" .Values.elasticsearch.master "ingest" .Values.elasticsearch.ingest "coordinator" .Values.elasticsearch.coordinator "data" .Values.elasticsearch.data }}

---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  labels: {{ include "mies.extralabels" $especificacion.extraLabels | nindent 4 -}}
    app: {{ include "mies.elasticsearchlabel" $ }}{{ $tipo_nodo }}

{{ end }}
